### ISSUE TITLE
Uncaught TypeError: e.indexOf is not a function

### ISSUE THREAD

**Issue by sergiuchuckmisha** [harshitkohli1997/xss-attack-detection#1]
when trying 
`
const attackDetection = require('xss-attack-detection');
const xss_detect = new attackDetection.xssAttackDetection();
xss_detect.detect("{}");
`

get following error:

`Uncaught TypeError: e.indexOf is not a function
    at i.docToFeatures (602-9c5ccdfe4be1238d2a75.js:1:56835)
    at i.getClassifications (602-9c5ccdfe4be1238d2a75.js:1:58085)
    at xssAttackDetection.detect (602-9c5ccdfe4be1238d2a75.js:1:111053)`

```
node --version
v12.22.12

```

**Comment by sergiuchuckmisha** [comment]
looks like, that this package is only for server-side, not for UI client

**Comment by sergiuchuckmisha** [comment]
looks like, that issues also take place also on server-side:

`/.../node_modules/bayes-classifier/lib/bayes-classifier.js:132
    features.push(Number(!!~doc.indexOf(feature)));
                                ^

TypeError: doc.indexOf is not a function
    at BayesClassifier.docToFeatures (/.../node_modules/bayes-classifier/lib/bayes-classifier.js:132:33)
    at BayesClassifier.getClassifications (/.../node_modules/bayes-classifier/lib/bayes-classifier.js:308:49)
    at xssAttackDetection.detect (/.../node_modules/xss-attack-detection/index.js:23:34)
    at IncomingMessage.<anonymous> (/.../server.js:901:41)
`
